version: '2'
services:
    db:
        build: ./db
        ports:
            - "5432:5432"
    nginx:
        build: ./nginx
        ports:
            - "80:80"
    redis:
        image: redis
        ports:
            - "6379"
    web:
        build: .
        volumes:
            - .:/myapp
        ports:
            - "80:80"
        depends_on:
            - nginx
            - redis
            - db

